### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by waiyanwh** [juliusv/prometheus-k8s-files#1]
When I create deployment with prometheus-deploymen.yml, with command 
```
kubectl apply -f prometheus-deployment.yml
```
this happen: 
```
error: unable to recognize "prometheus-deployment.yml": no matches for kind "Deployment" in version "extensions/v1beta1"
```

**Comment by juliusv** [comment]
Hi @waiyanwh in what context (or Kubernetes version) are you using these files? Is this as part of the Linux Foundation's online training course for Prometheus?

**Comment by waiyanwh** [comment]
> Hi @waiyanwh in what context (or Kubernetes version) are you using these files? Is this as part of the Linux Foundation's online training course for Prometheus?

Yes, it is a part of Linux Foundation Course. 
My docker  version  is 18.06.2~ce~3-0~ubuntu.
And kubeadm version:
```
kubeadm version: &version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:34:01Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juliusv** [comment]
@waiyanwh Thanks for letting me know! I just tested it. Indeed, new Kubernetes versions have removed the old `extensions/v1beta1` API version, so the files needed an update. I fixed both the Prometheus and demo service deployment files and pushed a fix (https://github.com/juliusv/prometheus-k8s-files/commit/099df6a898bbeee477ba32c1c3152b2c468254d0).

Could you try pulling (`git pull`) and applying the file again?

**Comment by waiyanwh** [comment]
@juliusv It's working well now. Thanks for the fix.

**Comment by juliusv** [comment]
Great, thanks :)
